apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faspo-online-data-service
  namespace: faspo-poc-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: faspopocacr.azurecr.io/helm
    chart: faspo-online-data-service
    targetRevision: 0.0.8
    helm:
      valuesObject:
        serviceAccount:
          name: faspo-poc-online-data-service-sa
        service:
          type: ClusterIP
          ports:
            - name: http
              port: 80
              targetPort: 8080
        env:
          - name: DATA_SOURCE_URL
            value: https://monitor.statnipokladna.gov.cz/api/monitorws
          - name: DATA_TARGET_URL
            value: http://faspo-store-service/api/v1/document
          - name: APPLICATIONINSIGHTS_STATSBEAT_DISABLED_ALL  # azure-sdk-for-python/issues/34804 @ GHB
            value: "true"
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            value: SW5zdHJ1bWVudGF0aW9uS2V5PTViYzU1YTU5LTZkZGMtNDJjZS05ZTU3LTQ4ODQ4YWZkZTU4NTtJbmdlc3Rpb25FbmRwb2ludD1odHRwczovL2dlcm1hbnl3ZXN0Y2VudHJhbC0xLmluLmFwcGxpY2F0aW9uaW5zaWdodHMuYXp1cmUuY29tLztMaXZlRW5kcG9pbnQ9aHR0cHM6Ly9nZXJtYW55d2VzdGNlbnRyYWwubGl2ZWRpYWdub3N0aWNzLm1vbml0b3IuYXp1cmUuY29tLztBcHBsaWNhdGlvbklkPTYzYzM5NTc4LWUxM2MtNGRkNS05OTMxLTVjMTFjMTU3MGI3OA==
            b64: true
  destination:
    server: https://kubernetes.default.svc
    namespace: faspo-poc-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
